CREATE TABLE IF NOT EXISTS online_matches (
    id VARCHAR(36) PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    current_snapshot_id VARCHAR(36) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS online_match_players (
    id VARCHAR(36) PRIMARY KEY,
    match_id VARCHAR(36) NOT NULL,
    player_id VARCHAR(36) NOT NULL,
    player_name VARCHAR(100) NOT NULL,
    color_assignment VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (match_id) REFERENCES online_matches(id) ON DELETE CASCADE
);
